---
# Job Market Analytics and Salary Prediction
---
---
## Notebook 1: Web Scraping
---

In [1]:
# Importing Libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import time
import random
from tqdm import tqdm

In [2]:
# Search Parameters
job_roles = [
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Business Analyst"
]

In [3]:
# Location
locations = [
    "Bangalore",
    "Hyderabad",
    "Pune",
    "Mumbai",
    "Delhi NCR",
    "Chennai"
]

In [4]:
# URL
for role in job_roles:

    role_url = role.lower().replace(" ", "-")
    role_query = role.lower().replace(" ", "+")

    for page in range(1, 4):

        if page == 1:
            url = f"https://www.naukri.com/{role_url}-jobs?k={role_query}"
        else:
            url = f"https://www.naukri.com/{role_url}-jobs-{page}?k={role_query}"

        print(url)

https://www.naukri.com/data-analyst-jobs?k=data+analyst
https://www.naukri.com/data-analyst-jobs-2?k=data+analyst
https://www.naukri.com/data-analyst-jobs-3?k=data+analyst
https://www.naukri.com/data-scientist-jobs?k=data+scientist
https://www.naukri.com/data-scientist-jobs-2?k=data+scientist
https://www.naukri.com/data-scientist-jobs-3?k=data+scientist
https://www.naukri.com/data-engineer-jobs?k=data+engineer
https://www.naukri.com/data-engineer-jobs-2?k=data+engineer
https://www.naukri.com/data-engineer-jobs-3?k=data+engineer
https://www.naukri.com/machine-learning-engineer-jobs?k=machine+learning+engineer
https://www.naukri.com/machine-learning-engineer-jobs-2?k=machine+learning+engineer
https://www.naukri.com/machine-learning-engineer-jobs-3?k=machine+learning+engineer
https://www.naukri.com/ai-engineer-jobs?k=ai+engineer
https://www.naukri.com/ai-engineer-jobs-2?k=ai+engineer
https://www.naukri.com/ai-engineer-jobs-3?k=ai+engineer
https://www.naukri.com/business-analyst-jobs?k=business+analyst
https://www.naukri.com/business-analyst-jobs-2?k=business+analyst
https://www.naukri.com/business-analyst-jobs-3?k=business+analyst

In [5]:
import requests

url = "https://www.naukri.com/data-analyst-jobs?k=data+analyst"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)
print(response.text[:500])

Status Code: 200
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><link rel="dns-prefetch" href="https://www.googletagmanager.com"/><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"/><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/0a5d062f8876df11.css" data-precedence="next"/><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="

In [6]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print("Number of titles found:",
      len(soup.find_all("a", class_="title")))

Number of titles found: 0

In [7]:
pip install selenium webdriver-manager

Requirement already satisfied: selenium in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (4.46.0)
Requirement already satisfied: webdriver-manager in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (4.1.2)
Requirement already satisfied: certifi>=2026.2.25 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from selenium) (2026.7.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.10)
Requirement already satisfied: outcome in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: exceptiongroup in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: requests in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from webdriver-manager) (2.32.5)
Requirement already satisfied: python-dotenv in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from webdriver-manager) (25.0)
Requirement already satisfied: pycparser in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sujal\anaconda3\envs\tf_env\lib\site-packages (from requests->webdriver-manager) (3.4.3)
Note: you may need to restart the kernel to use updated packages.

In [8]:
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.webdriver.chrome.service import Service

from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.chrome.options import Options

import pandas as pd
import time

In [9]:
options = Options()

options.add_argument("--start-maximized")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

In [10]:
url = "https://www.naukri.com/data-analyst-jobs?k=data+analyst"

driver.get(url)

time.sleep(5)

In [11]:
print(driver.page_source[:500])

<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/0a5d062f8876df11.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st

In [12]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(driver.page_source, "html.parser")

print(len(soup.find_all("a", class_="title")))

20

In [13]:
soup = BeautifulSoup(driver.page_source, "html.parser")

In [14]:
cards = soup.find_all("div")

print("Total divs:", len(cards))

for i in range(10):
    print(cards[i].get("class"))

Total divs: 696
None
['styles_srp-container__BXVFt', 'styles_srp-container--extra__hiLD3']
None
['nI-gNb-backdrop']
['nI-gNb-header']
['nI-gNb-header__placeholder']
['nI-gNb-header__wrapper']
[]
['nI-gNb-dropdown', 'nI-gNb-dropdown__c3', 'nI-gNb-Jobs']
[]

In [15]:
title = soup.find("a", class_="title")

print(title)

<a class="title" href="https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446" rel="noopener noreferrer" target="_blank" title="Climate Data Analyst">Climate Data Analyst</a>

In [16]:
print(title.parent)
print("=" * 100)
print(title.parent.parent)

<h2><a class="title" href="https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446" rel="noopener noreferrer" target="_blank" title="Climate Data Analyst">Climate Data Analyst</a></h2>
====================================================================================================
<div class="row1"><h2><a class="title" href="https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446" rel="noopener noreferrer" target="_blank" title="Climate Data Analyst">Climate Data Analyst</a></h2><span class="imagewrap"><img class="logoImage" loading="lazy" src="https://img.naukimg.com/logo_images/groups/v1/498434.gif"/></span></div>

In [17]:
parent = title

for i in range(8):
    parent = parent.parent
    print(f"\nLEVEL {i+1}")
    print(parent.name)
    print(parent.get("class"))

LEVEL 1
h2
None

LEVEL 2
div
['row1']

LEVEL 3
div
['cust-job-tuple', 'layout-wrapper', 'lay-2', 'sjw__tuple']

LEVEL 4
div
['srp-jobtuple-wrapper']

LEVEL 5
div
['styles_jlc__main__VdwtF']

LEVEL 6
div
['styles_job-listing-container__OCfZC']

LEVEL 7
div
['styles_middle-section-container__iteRZ']

LEVEL 8
div
['styles_srpc__content__h6cyr']

In [18]:
job_cards = soup.find_all("div", class_="cust-job-tuple")
print("Number of job cards:", len(job_cards))

Number of job cards: 20

In [19]:
print(job_cards[0].prettify())

<div class="cust-job-tuple layout-wrapper lay-2 sjw__tuple">
 <div class="row1">
  <h2>
   <a class="title" href="https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446" rel="noopener noreferrer" target="_blank" title="Climate Data Analyst">
    Climate Data Analyst
   </a>
  </h2>
  <span class="imagewrap">
   <img class="logoImage" loading="lazy" src="https://img.naukimg.com/logo_images/groups/v1/498434.gif"/>
  </span>
 </div>
 <div class="row2">
  <span class="comp-dtls-wrap">
   <a class="comp-name mw-25" href="https://www.naukri.com/msci-services-jobs-careers-754894" target="_blank" title="MSCI Services">
    MSCI Services
   </a>
   <a class="rating" href="https://www.ambitionbox.com/reviews/msci-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star star">
    </span>
    <span class="main-2">
     3.6
    </span>
    <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star">
    </span>
   </a>
   <a class="review ver-line" href="https://www.ambitionbox.com/reviews/msci-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
    392  Reviews
   </a>
  </span>
 </div>
 <div class="row3">
  <div class="job-details">
   <span class="exp-wrap">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-experience exp">
     <span class="expwdth" title="0-4 Yrs ">
      0-4 Yrs
     </span>
    </span>
   </span>
   <span class="loc-wrap ver-line">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-location loc">
     <span class="locWdth" title="Pune ">
      Pune
     </span>
    </span>
   </span>
  </div>
 </div>
 <div class="row4">
  <span class="job-desc ni-job-tuple-icon ni-job-tuple-icon-srp-description">
   The Climate Data and Content team is responsible for research and assessment of carbon...
  </span>
 </div>
 <div class="row5">
  <ul class="tags-gt">
   <li class="dot-gt tag-li">
    data operations
   </li>
   <li class="dot-gt tag-li">
    data analysis
   </li>
   <li class="dot-gt tag-li">
    data analytics
   </li>
   <li class="dot-gt tag-li">
    workflow
   </li>
   <li class="dot-gt tag-li">
    data research
   </li>
   <li class="dot-gt tag-li">
    pivot table
   </li>
   <li class="dot-gt tag-li">
    data integrity
   </li>
   <li class="dot-gt tag-li">
    research
   </li>
  </ul>
 </div>
 <div class="row6">
  <span class="job-post-day">
   3 weeks ago
  </span>
  <span class="ni-job-tuple-icon ni-job-tuple-icon-srpSaveUnfilled un-saved save-job-tag">
   save
  </span>
 </div>
</div>

In [20]:
job = job_cards[0]

In [21]:
title = job.find("a", class_="title")

job_title = title.text.strip()

job_link = title["href"]

print(job_title)
print(job_link)

Climate Data Analyst
https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446

In [22]:
company = job.find("a", class_="comp-name")

print(company)

<a class="comp-name mw-25" href="https://www.naukri.com/msci-services-jobs-careers-754894" target="_blank" title="MSCI Services">MSCI Services</a>

In [23]:
company_name = company.text.strip()

print(company_name)

MSCI Services

In [24]:
experience = job.find("span", class_="expwdth")

print(experience)

<span class="expwdth" title="0-4 Yrs ">0-4 Yrs</span>

In [25]:
salary = job.find("span", class_="sal-wrap")

print(salary)

None

In [26]:
location = job.find("span", class_="locWdth")

print(location)

<span class="locWdth" title="Pune ">Pune</span>

In [27]:
print(job.prettify())

<div class="cust-job-tuple layout-wrapper lay-2 sjw__tuple">
 <div class="row1">
  <h2>
   <a class="title" href="https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446" rel="noopener noreferrer" target="_blank" title="Climate Data Analyst">
    Climate Data Analyst
   </a>
  </h2>
  <span class="imagewrap">
   <img class="logoImage" loading="lazy" src="https://img.naukimg.com/logo_images/groups/v1/498434.gif"/>
  </span>
 </div>
 <div class="row2">
  <span class="comp-dtls-wrap">
   <a class="comp-name mw-25" href="https://www.naukri.com/msci-services-jobs-careers-754894" target="_blank" title="MSCI Services">
    MSCI Services
   </a>
   <a class="rating" href="https://www.ambitionbox.com/reviews/msci-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star star">
    </span>
    <span class="main-2">
     3.6
    </span>
    <span class="ni-job-tuple-icon ni-job-tuple-icon-ot_star">
    </span>
   </a>
   <a class="review ver-line" href="https://www.ambitionbox.com/reviews/msci-reviews?utm_campaign=srp_ratings&amp;utm_medium=desktop&amp;utm_source=naukri" target="_blank" title="Powered by Ambition Box">
    392  Reviews
   </a>
  </span>
 </div>
 <div class="row3">
  <div class="job-details">
   <span class="exp-wrap">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-experience exp">
     <span class="expwdth" title="0-4 Yrs ">
      0-4 Yrs
     </span>
    </span>
   </span>
   <span class="loc-wrap ver-line">
    <span class="ni-job-tuple-icon ni-job-tuple-icon-srp-location loc">
     <span class="locWdth" title="Pune ">
      Pune
     </span>
    </span>
   </span>
  </div>
 </div>
 <div class="row4">
  <span class="job-desc ni-job-tuple-icon ni-job-tuple-icon-srp-description">
   The Climate Data and Content team is responsible for research and assessment of carbon...
  </span>
 </div>
 <div class="row5">
  <ul class="tags-gt">
   <li class="dot-gt tag-li">
    data operations
   </li>
   <li class="dot-gt tag-li">
    data analysis
   </li>
   <li class="dot-gt tag-li">
    data analytics
   </li>
   <li class="dot-gt tag-li">
    workflow
   </li>
   <li class="dot-gt tag-li">
    data research
   </li>
   <li class="dot-gt tag-li">
    pivot table
   </li>
   <li class="dot-gt tag-li">
    data integrity
   </li>
   <li class="dot-gt tag-li">
    research
   </li>
  </ul>
 </div>
 <div class="row6">
  <span class="job-post-day">
   3 weeks ago
  </span>
  <span class="ni-job-tuple-icon ni-job-tuple-icon-srpSaveUnfilled un-saved save-job-tag">
   save
  </span>
 </div>
</div>

### Extracting Each Field

In [28]:
# Job Title
title_tag = job.find("a", class_="title")
job_title = title_tag.text.strip()
job_link = title_tag["href"]

In [29]:
# Company Name
company_tag = job.find("a", class_="comp-name")
company = company_tag.text.strip()

In [30]:
# Rating
rating_tag = job.find("span", class_="main-2")
rating = rating_tag.text.strip() if rating_tag else None

In [31]:
# Reviews
review_tag = job.find("a", class_="review")
reviews = review_tag.text.strip() if review_tag else None

In [32]:
# Experience
experience_tag = job.find("span", class_="expwdth")
experience = experience_tag.text.strip()

In [33]:
# Salary
salary_tag = job.find("span", class_="sal-wrap")
salary = salary_tag.text.strip() if salary_tag else "Not Disclosed"

In [34]:
# Location
location_tag = job.find("span", class_="locWdth")
location = location_tag.text.strip()

In [35]:
# Description
description_tag = job.find("span", class_="job-desc")
description = description_tag.text.strip()

In [36]:
# Skills
skills = job.find_all("li", class_="tag-li")
skills = ", ".join(skill.text.strip() for skill in skills)

In [37]:
# Posted Date
posted_tag = job.find("span", class_="job-post-day")
posted = posted_tag.text.strip()

In [38]:
print(job_title)
print(company)
print(rating)
print(reviews)
print(experience)
print(salary)
print(location)
print(description)
print(skills)
print(posted)
print(job_link)

Climate Data Analyst
MSCI Services
3.6
392  Reviews
0-4 Yrs
Not Disclosed
Pune
The Climate Data and Content team is responsible for research and assessment of carbon...
data operations, data analysis, data analytics, workflow, data research, pivot table, data integrity, research
3 weeks ago
https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446

In [39]:
# Storing in a Dictionary
job_data = {
    "Job Title": job_title,
    "Company": company,
    "Rating": rating,
    "Reviews": reviews,
    "Experience": experience,
    "Salary": salary,
    "Location": location,
    "Description": description,
    "Skills": skills,
    "Posted": posted,
    "Job Link": job_link
}

In [40]:
print(job_data)

{'Job Title': 'Climate Data Analyst', 'Company': 'MSCI Services', 'Rating': '3.6', 'Reviews': '392  Reviews', 'Experience': '0-4 Yrs', 'Salary': 'Not Disclosed', 'Location': 'Pune', 'Description': 'The Climate Data and Content team is responsible for research and assessment of carbon...', 'Skills': 'data operations, data analysis, data analytics, workflow, data research, pivot table, data integrity, research', 'Posted': '3 weeks ago', 'Job Link': 'https://www.naukri.com/job-listings-climate-data-analyst-msci-services-pvt-ltd-pune-0-to-4-years-090726505446'}

In [41]:
# Scrapping
jobs = []

for role in job_roles:

    role_url = role.lower().replace(" ", "-")
    role_query = role.lower().replace(" ", "+")

    for page in range(1, 51):

        if page == 1:
            url = f"https://www.naukri.com/{role_url}-jobs?k={role_query}"
        else:
            url = f"https://www.naukri.com/{role_url}-jobs-{page}?k={role_query}"

        driver.get(url)
        time.sleep(2)

        soup = BeautifulSoup(driver.page_source, "html.parser")

        job_cards = soup.find_all("div", class_="cust-job-tuple")

        for job in job_cards:

            title_tag = job.find("a", class_="title") 
            if not title_tag: 
                continue
            company_tag = job.find("a", class_="comp-name")
            rating_tag = job.find("span", class_="main-2")
            review_tag = job.find("a", class_="review")
            experience_tag = job.find("span", class_="expwdth")
            salary_tag = job.find("span", class_="sal-wrap")
            location_tag = job.find("span", class_="locWdth")
            description_tag = job.find("span", class_="job-desc")
            posted_tag = job.find("span", class_="job-post-day")

            skills = job.find_all("li", class_="tag-li")
            if not title_tag.get("href"):
                print(f"Missing href | Role: {role} | Page: {page}")
                print(title_tag)
                continue
            jobs.append({
                "Role Searched": role,
                "Job Title": title_tag.text.strip() if title_tag else None,
                "Company": company_tag.text.strip() if company_tag else None,
                "Rating": rating_tag.text.strip() if rating_tag else None,
                "Reviews": review_tag.text.strip() if review_tag else None,
                "Experience": experience_tag.text.strip() if experience_tag else None,
                "Salary": salary_tag.text.strip() if salary_tag else "Not Disclosed",
                "Location": location_tag.text.strip() if location_tag else None,
                "Description": description_tag.text.strip() if description_tag else None,
                "Skills": ", ".join(skill.text.strip() for skill in skills),
                "Posted": posted_tag.text.strip() if posted_tag else None,
                "Job Link": title_tag.get("href") if title_tag else None
            })

        print(f"{role} | Page {page} | Total Jobs: {len(jobs)}")

Data Analyst | Page 1 | Total Jobs: 20
Data Analyst | Page 2 | Total Jobs: 20
Data Analyst | Page 3 | Total Jobs: 40
Data Analyst | Page 4 | Total Jobs: 60
Data Analyst | Page 5 | Total Jobs: 80
Data Analyst | Page 6 | Total Jobs: 100
Data Analyst | Page 7 | Total Jobs: 120
Data Analyst | Page 8 | Total Jobs: 120
Data Analyst | Page 9 | Total Jobs: 140
Data Analyst | Page 10 | Total Jobs: 160
Data Analyst | Page 11 | Total Jobs: 179
Data Analyst | Page 12 | Total Jobs: 199
Data Analyst | Page 13 | Total Jobs: 199
Data Analyst | Page 14 | Total Jobs: 219
Data Analyst | Page 15 | Total Jobs: 239
Data Analyst | Page 16 | Total Jobs: 258
Data Analyst | Page 17 | Total Jobs: 278
Data Analyst | Page 18 | Total Jobs: 298
Data Analyst | Page 19 | Total Jobs: 318
Data Analyst | Page 20 | Total Jobs: 338
Data Analyst | Page 21 | Total Jobs: 358
Data Analyst | Page 22 | Total Jobs: 378
Data Analyst | Page 23 | Total Jobs: 398
Data Analyst | Page 24 | Total Jobs: 418
Data Analyst | Page 25 | Total Jobs: 438
Data Analyst | Page 26 | Total Jobs: 458
Data Analyst | Page 27 | Total Jobs: 478
Data Analyst | Page 28 | Total Jobs: 498
Data Analyst | Page 29 | Total Jobs: 518
Data Analyst | Page 30 | Total Jobs: 538
Data Analyst | Page 31 | Total Jobs: 558
Data Analyst | Page 32 | Total Jobs: 578
Data Analyst | Page 33 | Total Jobs: 598
Data Analyst | Page 34 | Total Jobs: 618
Data Analyst | Page 35 | Total Jobs: 638
Data Analyst | Page 36 | Total Jobs: 658
Data Analyst | Page 37 | Total Jobs: 658
Data Analyst | Page 38 | Total Jobs: 658
Data Analyst | Page 39 | Total Jobs: 678
Data Analyst | Page 40 | Total Jobs: 698
Data Analyst | Page 41 | Total Jobs: 718
Data Analyst | Page 42 | Total Jobs: 738
Data Analyst | Page 43 | Total Jobs: 758
Data Analyst | Page 44 | Total Jobs: 758
Data Analyst | Page 45 | Total Jobs: 778
Data Analyst | Page 46 | Total Jobs: 798
Data Analyst | Page 47 | Total Jobs: 798
Data Analyst | Page 48 | Total Jobs: 818
Data Analyst | Page 49 | Total Jobs: 818
Data Analyst | Page 50 | Total Jobs: 838
Data Scientist | Page 1 | Total Jobs: 858
Data Scientist | Page 2 | Total Jobs: 878
Data Scientist | Page 3 | Total Jobs: 898
Data Scientist | Page 4 | Total Jobs: 918
Data Scientist | Page 5 | Total Jobs: 938
Data Scientist | Page 6 | Total Jobs: 958
Data Scientist | Page 7 | Total Jobs: 978
Data Scientist | Page 8 | Total Jobs: 998
Data Scientist | Page 9 | Total Jobs: 1018
Data Scientist | Page 10 | Total Jobs: 1038
Data Scientist | Page 11 | Total Jobs: 1058
Data Scientist | Page 12 | Total Jobs: 1078
Data Scientist | Page 13 | Total Jobs: 1098
Data Scientist | Page 14 | Total Jobs: 1118
Data Scientist | Page 15 | Total Jobs: 1138
Data Scientist | Page 16 | Total Jobs: 1158
Data Scientist | Page 17 | Total Jobs: 1178
Data Scientist | Page 18 | Total Jobs: 1197
Data Scientist | Page 19 | Total Jobs: 1217
Data Scientist | Page 20 | Total Jobs: 1237
Data Scientist | Page 21 | Total Jobs: 1257
Data Scientist | Page 22 | Total Jobs: 1277
Data Scientist | Page 23 | Total Jobs: 1297
Data Scientist | Page 24 | Total Jobs: 1317
Data Scientist | Page 25 | Total Jobs: 1337
Data Scientist | Page 26 | Total Jobs: 1357
Data Scientist | Page 27 | Total Jobs: 1377
Data Scientist | Page 28 | Total Jobs: 1397
Data Scientist | Page 29 | Total Jobs: 1417
Data Scientist | Page 30 | Total Jobs: 1437
Data Scientist | Page 31 | Total Jobs: 1457
Data Scientist | Page 32 | Total Jobs: 1477
Data Scientist | Page 33 | Total Jobs: 1497
Data Scientist | Page 34 | Total Jobs: 1517
Data Scientist | Page 35 | Total Jobs: 1537
Data Scientist | Page 36 | Total Jobs: 1557
Data Scientist | Page 37 | Total Jobs: 1577
Data Scientist | Page 38 | Total Jobs: 1597
Data Scientist | Page 39 | Total Jobs: 1617
Data Scientist | Page 40 | Total Jobs: 1637
Data Scientist | Page 41 | Total Jobs: 1657
Data Scientist | Page 42 | Total Jobs: 1677
Data Scientist | Page 43 | Total Jobs: 1697
Data Scientist | Page 44 | Total Jobs: 1717
Data Scientist | Page 45 | Total Jobs: 1737
Data Scientist | Page 46 | Total Jobs: 1757
Data Scientist | Page 47 | Total Jobs: 1777
Data Scientist | Page 48 | Total Jobs: 1797
Data Scientist | Page 49 | Total Jobs: 1817
Data Scientist | Page 50 | Total Jobs: 1837
Data Engineer | Page 1 | Total Jobs: 1857
Data Engineer | Page 2 | Total Jobs: 1877
Data Engineer | Page 3 | Total Jobs: 1877
Data Engineer | Page 4 | Total Jobs: 1877
Data Engineer | Page 5 | Total Jobs: 1897
Data Engineer | Page 6 | Total Jobs: 1917
Data Engineer | Page 7 | Total Jobs: 1937
Data Engineer | Page 8 | Total Jobs: 1957
Data Engineer | Page 9 | Total Jobs: 1977
Data Engineer | Page 10 | Total Jobs: 1997
Data Engineer | Page 11 | Total Jobs: 2017
Data Engineer | Page 12 | Total Jobs: 2017
Data Engineer | Page 13 | Total Jobs: 2037
Data Engineer | Page 14 | Total Jobs: 2057
Data Engineer | Page 15 | Total Jobs: 2077
Data Engineer | Page 16 | Total Jobs: 2097
Data Engineer | Page 17 | Total Jobs: 2117
Data Engineer | Page 18 | Total Jobs: 2137
Data Engineer | Page 19 | Total Jobs: 2157
Data Engineer | Page 20 | Total Jobs: 2177
Data Engineer | Page 21 | Total Jobs: 2197
Data Engineer | Page 22 | Total Jobs: 2217
Data Engineer | Page 23 | Total Jobs: 2237
Data Engineer | Page 24 | Total Jobs: 2257
Data Engineer | Page 25 | Total Jobs: 2257
Data Engineer | Page 26 | Total Jobs: 2277
Data Engineer | Page 27 | Total Jobs: 2277
Data Engineer | Page 28 | Total Jobs: 2277
Data Engineer | Page 29 | Total Jobs: 2277
Data Engineer | Page 30 | Total Jobs: 2277
Data Engineer | Page 31 | Total Jobs: 2277
Data Engineer | Page 32 | Total Jobs: 2277
Data Engineer | Page 33 | Total Jobs: 2277
Data Engineer | Page 34 | Total Jobs: 2277
Data Engineer | Page 35 | Total Jobs: 2297
Data Engineer | Page 36 | Total Jobs: 2297
Data Engineer | Page 37 | Total Jobs: 2297
Data Engineer | Page 38 | Total Jobs: 2317
Data Engineer | Page 39 | Total Jobs: 2317
Data Engineer | Page 40 | Total Jobs: 2337
Data Engineer | Page 41 | Total Jobs: 2357
Data Engineer | Page 42 | Total Jobs: 2377
Data Engineer | Page 43 | Total Jobs: 2377
Data Engineer | Page 44 | Total Jobs: 2397
Data Engineer | Page 45 | Total Jobs: 2417
Data Engineer | Page 46 | Total Jobs: 2437
Data Engineer | Page 47 | Total Jobs: 2457
Data Engineer | Page 48 | Total Jobs: 2457
Data Engineer | Page 49 | Total Jobs: 2477
Data Engineer | Page 50 | Total Jobs: 2497
Machine Learning Engineer | Page 1 | Total Jobs: 2517
Machine Learning Engineer | Page 2 | Total Jobs: 2537
Machine Learning Engineer | Page 3 | Total Jobs: 2557
Machine Learning Engineer | Page 4 | Total Jobs: 2557
Machine Learning Engineer | Page 5 | Total Jobs: 2577
Machine Learning Engineer | Page 6 | Total Jobs: 2597
Machine Learning Engineer | Page 7 | Total Jobs: 2617
Machine Learning Engineer | Page 8 | Total Jobs: 2617
Machine Learning Engineer | Page 9 | Total Jobs: 2637
Machine Learning Engineer | Page 10 | Total Jobs: 2657
Machine Learning Engineer | Page 11 | Total Jobs: 2677
Machine Learning Engineer | Page 12 | Total Jobs: 2697
Machine Learning Engineer | Page 13 | Total Jobs: 2717
Machine Learning Engineer | Page 14 | Total Jobs: 2737
Machine Learning Engineer | Page 15 | Total Jobs: 2757
Machine Learning Engineer | Page 16 | Total Jobs: 2777
Machine Learning Engineer | Page 17 | Total Jobs: 2797
Machine Learning Engineer | Page 18 | Total Jobs: 2817
Machine Learning Engineer | Page 19 | Total Jobs: 2837
Machine Learning Engineer | Page 20 | Total Jobs: 2857
Machine Learning Engineer | Page 21 | Total Jobs: 2877
Machine Learning Engineer | Page 22 | Total Jobs: 2897
Machine Learning Engineer | Page 23 | Total Jobs: 2917
Machine Learning Engineer | Page 24 | Total Jobs: 2937
Machine Learning Engineer | Page 25 | Total Jobs: 2957
Machine Learning Engineer | Page 26 | Total Jobs: 2977
Machine Learning Engineer | Page 27 | Total Jobs: 2997
Machine Learning Engineer | Page 28 | Total Jobs: 3017
Machine Learning Engineer | Page 29 | Total Jobs: 3017
Machine Learning Engineer | Page 30 | Total Jobs: 3037
Machine Learning Engineer | Page 31 | Total Jobs: 3057
Machine Learning Engineer | Page 32 | Total Jobs: 3077
Machine Learning Engineer | Page 33 | Total Jobs: 3096
Machine Learning Engineer | Page 34 | Total Jobs: 3116
Machine Learning Engineer | Page 35 | Total Jobs: 3136
Machine Learning Engineer | Page 36 | Total Jobs: 3136
Machine Learning Engineer | Page 37 | Total Jobs: 3156
Machine Learning Engineer | Page 38 | Total Jobs: 3176
Machine Learning Engineer | Page 39 | Total Jobs: 3196
Machine Learning Engineer | Page 40 | Total Jobs: 3216
Machine Learning Engineer | Page 41 | Total Jobs: 3236
Machine Learning Engineer | Page 42 | Total Jobs: 3236
Machine Learning Engineer | Page 43 | Total Jobs: 3256
Machine Learning Engineer | Page 44 | Total Jobs: 3276
Machine Learning Engineer | Page 45 | Total Jobs: 3296
Machine Learning Engineer | Page 46 | Total Jobs: 3316
Machine Learning Engineer | Page 47 | Total Jobs: 3316
Machine Learning Engineer | Page 48 | Total Jobs: 3336
Machine Learning Engineer | Page 49 | Total Jobs: 3356
Machine Learning Engineer | Page 50 | Total Jobs: 3376
AI Engineer | Page 1 | Total Jobs: 3376
AI Engineer | Page 2 | Total Jobs: 3396
AI Engineer | Page 3 | Total Jobs: 3416
AI Engineer | Page 4 | Total Jobs: 3416
AI Engineer | Page 5 | Total Jobs: 3436
AI Engineer | Page 6 | Total Jobs: 3436
AI Engineer | Page 7 | Total Jobs: 3456
AI Engineer | Page 8 | Total Jobs: 3456
AI Engineer | Page 9 | Total Jobs: 3476
AI Engineer | Page 10 | Total Jobs: 3476
AI Engineer | Page 11 | Total Jobs: 3496
AI Engineer | Page 12 | Total Jobs: 3516
AI Engineer | Page 13 | Total Jobs: 3536
AI Engineer | Page 14 | Total Jobs: 3536
AI Engineer | Page 15 | Total Jobs: 3536
AI Engineer | Page 16 | Total Jobs: 3556
AI Engineer | Page 17 | Total Jobs: 3556
AI Engineer | Page 18 | Total Jobs: 3556
AI Engineer | Page 19 | Total Jobs: 3576
AI Engineer | Page 20 | Total Jobs: 3576
AI Engineer | Page 21 | Total Jobs: 3576
AI Engineer | Page 22 | Total Jobs: 3576
AI Engineer | Page 23 | Total Jobs: 3596
AI Engineer | Page 24 | Total Jobs: 3596
AI Engineer | Page 25 | Total Jobs: 3596
AI Engineer | Page 26 | Total Jobs: 3616
AI Engineer | Page 27 | Total Jobs: 3616
AI Engineer | Page 28 | Total Jobs: 3616
AI Engineer | Page 29 | Total Jobs: 3616
AI Engineer | Page 30 | Total Jobs: 3616
AI Engineer | Page 31 | Total Jobs: 3636
AI Engineer | Page 32 | Total Jobs: 3636
AI Engineer | Page 33 | Total Jobs: 3636
AI Engineer | Page 34 | Total Jobs: 3636
AI Engineer | Page 35 | Total Jobs: 3636
AI Engineer | Page 36 | Total Jobs: 3636
AI Engineer | Page 37 | Total Jobs: 3636
AI Engineer | Page 38 | Total Jobs: 3636
AI Engineer | Page 39 | Total Jobs: 3636
AI Engineer | Page 40 | Total Jobs: 3636
AI Engineer | Page 41 | Total Jobs: 3636
AI Engineer | Page 42 | Total Jobs: 3636
AI Engineer | Page 43 | Total Jobs: 3656
AI Engineer | Page 44 | Total Jobs: 3656
AI Engineer | Page 45 | Total Jobs: 3656
AI Engineer | Page 46 | Total Jobs: 3656
AI Engineer | Page 47 | Total Jobs: 3676
AI Engineer | Page 48 | Total Jobs: 3696
AI Engineer | Page 49 | Total Jobs: 3696
AI Engineer | Page 50 | Total Jobs: 3696
Business Analyst | Page 1 | Total Jobs: 3696
Business Analyst | Page 2 | Total Jobs: 3696
Business Analyst | Page 3 | Total Jobs: 3696
Business Analyst | Page 4 | Total Jobs: 3696
Business Analyst | Page 5 | Total Jobs: 3716
Business Analyst | Page 6 | Total Jobs: 3716
Business Analyst | Page 7 | Total Jobs: 3736
Business Analyst | Page 8 | Total Jobs: 3736
Business Analyst | Page 9 | Total Jobs: 3756
Business Analyst | Page 10 | Total Jobs: 3776
Business Analyst | Page 11 | Total Jobs: 3796
Business Analyst | Page 12 | Total Jobs: 3796
Business Analyst | Page 13 | Total Jobs: 3796
Business Analyst | Page 14 | Total Jobs: 3796
Business Analyst | Page 15 | Total Jobs: 3796
Business Analyst | Page 16 | Total Jobs: 3816
Business Analyst | Page 17 | Total Jobs: 3836
Business Analyst | Page 18 | Total Jobs: 3836
Business Analyst | Page 19 | Total Jobs: 3856
Business Analyst | Page 20 | Total Jobs: 3876
Business Analyst | Page 21 | Total Jobs: 3896
Business Analyst | Page 22 | Total Jobs: 3916
Business Analyst | Page 23 | Total Jobs: 3936
Business Analyst | Page 24 | Total Jobs: 3936
Business Analyst | Page 25 | Total Jobs: 3936
Business Analyst | Page 26 | Total Jobs: 3956
Business Analyst | Page 27 | Total Jobs: 3976
Business Analyst | Page 28 | Total Jobs: 3976
Business Analyst | Page 29 | Total Jobs: 3976
Business Analyst | Page 30 | Total Jobs: 3996
Business Analyst | Page 31 | Total Jobs: 4016
Business Analyst | Page 32 | Total Jobs: 4016
Business Analyst | Page 33 | Total Jobs: 4036
Business Analyst | Page 34 | Total Jobs: 4036
Business Analyst | Page 35 | Total Jobs: 4036
Business Analyst | Page 36 | Total Jobs: 4036
Business Analyst | Page 37 | Total Jobs: 4056
Business Analyst | Page 38 | Total Jobs: 4076
Business Analyst | Page 39 | Total Jobs: 4096
Business Analyst | Page 40 | Total Jobs: 4096
Business Analyst | Page 41 | Total Jobs: 4096
Business Analyst | Page 42 | Total Jobs: 4096
Business Analyst | Page 43 | Total Jobs: 4096
Business Analyst | Page 44 | Total Jobs: 4096
Business Analyst | Page 45 | Total Jobs: 4096
Business Analyst | Page 46 | Total Jobs: 4096
Business Analyst | Page 47 | Total Jobs: 4096
Business Analyst | Page 48 | Total Jobs: 4096
Business Analyst | Page 49 | Total Jobs: 4116
Business Analyst | Page 50 | Total Jobs: 4136

In [51]:
df = pd.DataFrame(jobs)

print(df.shape)

df.to_csv("naukri_jobs.csv", index=False)

(4136, 12)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4136 entries, 0 to 4135
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Role Searched  4136 non-null   object
 1   Job Title      4136 non-null   object
 2   Company        4136 non-null   object
 3   Rating         3177 non-null   object
 4   Reviews        3177 non-null   object
 5   Experience     4084 non-null   object
 6   Salary         4136 non-null   object
 7   Location       4114 non-null   object
 8   Description    4106 non-null   object
 9   Skills         4136 non-null   object
 10  Posted         4136 non-null   object
 11  Job Link       4136 non-null   object
dtypes: object(12)
memory usage: 387.9+ KB

In [53]:
df.head()

,Role Searched,Job Title,Company,Rating,Reviews,Experience,Salary,Location,Description,Skills,Posted,Job Link
0,Data Analyst,Climate Data Analyst,MSCI Services,3.6,392 Reviews,0-4 Yrs,Not Disclosed,Pune,The Climate Data and Content team is responsib...,"data operations, data analysis, data analytics...",3 weeks ago,https://www.naukri.com/job-listings-climate-da...
1,Data Analyst,Data Analyst,Snapdeal,3.6,673 Reviews,1-6 Yrs,Not Disclosed,Gurugram,Providing technical expertise in data storage ...,"master data, python, metadata, data analysis, ...",3+ weeks ago,https://www.naukri.com/job-listings-data-analy...
2,Data Analyst,Data Analyst,Cognizant,3.7,63144 Reviews,5-10 Yrs,Not Disclosed,Hyderabad,Role: Data AnalystExperience: 5+ years Preferr...,"Data Analysis, Data Visualization, Advanced Ex...",1 week ago,https://www.naukri.com/job-listings-data-analy...
3,Data Analyst,Data Analyst,MNC,None,None,0-2 Yrs,2.25-3.5 Lacs PA,"Pimpri-Chinchwad, Pune",We are looking for a motivated and detail-orie...,"Google Sheets, Power BI, MS Office, Data Analy...",2 days ago,https://www.naukri.com/job-listings-data-analy...
4,Data Analyst,Data Analyst (English Required),Peroptyx,3.2,17 Reviews,0-5 Yrs,Not Disclosed,Remote,"For thousands of years, maps have provided hum...","Data Analysis, English, Data Analytics, Data M...",2 weeks ago,https://www.naukri.com/job-listings-data-analy...

In [54]:
print("="*50)
print("Web Scraping Completed Successfully")
print("="*50)

print(f"Total Records Collected : {len(df)}")
print(f"Total Columns : {len(df.columns)}")

print("\nColumns:")
print(df.columns.tolist())

print("\nDataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
display(df.head())

==================================================
Web Scraping Completed Successfully
==================================================
Total Records Collected : 4136
Total Columns : 12

Columns:
['Role Searched', 'Job Title', 'Company', 'Rating', 'Reviews', 'Experience', 'Salary', 'Location', 'Description', 'Skills', 'Posted', 'Job Link']

Dataset Shape:
(4136, 12)

First 5 Rows:

,Role Searched,Job Title,Company,Rating,Reviews,Experience,Salary,Location,Description,Skills,Posted,Job Link
0,Data Analyst,Climate Data Analyst,MSCI Services,3.6,392 Reviews,0-4 Yrs,Not Disclosed,Pune,The Climate Data and Content team is responsib...,"data operations, data analysis, data analytics...",3 weeks ago,https://www.naukri.com/job-listings-climate-da...
1,Data Analyst,Data Analyst,Snapdeal,3.6,673 Reviews,1-6 Yrs,Not Disclosed,Gurugram,Providing technical expertise in data storage ...,"master data, python, metadata, data analysis, ...",3+ weeks ago,https://www.naukri.com/job-listings-data-analy...
2,Data Analyst,Data Analyst,Cognizant,3.7,63144 Reviews,5-10 Yrs,Not Disclosed,Hyderabad,Role: Data AnalystExperience: 5+ years Preferr...,"Data Analysis, Data Visualization, Advanced Ex...",1 week ago,https://www.naukri.com/job-listings-data-analy...
3,Data Analyst,Data Analyst,MNC,None,None,0-2 Yrs,2.25-3.5 Lacs PA,"Pimpri-Chinchwad, Pune",We are looking for a motivated and detail-orie...,"Google Sheets, Power BI, MS Office, Data Analy...",2 days ago,https://www.naukri.com/job-listings-data-analy...
4,Data Analyst,Data Analyst (English Required),Peroptyx,3.2,17 Reviews,0-5 Yrs,Not Disclosed,Remote,"For thousands of years, maps have provided hum...","Data Analysis, English, Data Analytics, Data M...",2 weeks ago,https://www.naukri.com/job-listings-data-analy...

### **Explanation -**
In the first notebook, I developed an automated web scraping pipeline to collect real-world job market data from Naukri.com. Since the objective of the project was to analyse the Indian job market for data-related roles, I selected six relevant search categories: Data Analyst, Data Scientist, Data Engineer, Machine Learning Engineer, AI Engineer, and Business Analyst. These roles cover a broad spectrum of the analytics and AI industry, making the dataset representative of current hiring trends.

Initially, I explored using the Requests library with BeautifulSoup, but inspection of the returned HTML revealed that Naukri loads job listings dynamically using JavaScript (React/Next.js). As a result, the required job information was not present in the raw HTML, making traditional web scraping ineffective. To overcome this, I used Selenium WebDriver, which automates a real browser, allowing the page to load completely before extracting its HTML. Once the page was rendered, BeautifulSoup was used to efficiently parse the HTML because it is faster and simpler than locating every element directly through Selenium.

The scraper automatically navigated through multiple pages for each job role and extracted important attributes such as job title, company name, company rating, number of reviews, experience required, salary, location, job description, required skills, posting time, and job link. Some companies did not display ratings or salaries, so the scraper intentionally preserved these missing values instead of replacing them, ensuring that the dataset accurately reflected the information available on the website. The final output consisted of 4,136 job postings stored as a CSV file, providing a comprehensive real-world dataset for further preprocessing, analysis, and predictive modelling.